// src/lib/components/terminal/TerminalPage.tsx
import "@xterm/xterm/css/xterm.css";
import { useEffect, useRef, useState } from "react";
import { Plus, Terminal as TerminalIcon, X } from "lucide-react";
import ProjectPicker from "$lib/components/shared/ProjectPicker";
import { ActionButton } from "$lib/components/shared/PageScaffold";
import { useProjectContextStore } from "$lib/stores/project-context";
import {
  attachToContainer,
  closeSession,
  createSession,
  detachFromContainer,
  fitActiveSession,
  getActiveSession,
  useTerminalStore,
} from "$lib/stores/terminal";

export default function TerminalPage() {
  const containerRef = useRef<HTMLDivElement | null>(null);
  const projectPath = useProjectContextStore((s) => s.selectedProjectPath);
  const sessions = useTerminalStore((s) => s.sessions);
  const activeId = useTerminalStore((s) => s.activeSessionId);
  const switchSession = useTerminalStore((s) => s.switchSession);
  const [starting, setStarting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const projectName = projectPath ? (projectPath.split("/").pop() ?? projectPath) : "";

  async function startNew() {
    if (!projectPath || starting) return;
    setStarting(true);
    setError(null);
    try {
      await createSession(projectPath, projectName);
      requestAnimationFrame(() => {
        if (containerRef.current) attachToContainer(containerRef.current);
      });
    } catch (e) {
      setError(`Failed to start: ${e}`);
    } finally {
      setStarting(false);
    }
  }

  function selectSession(id: string) {
    detachFromContainer();
    switchSession(id);
    requestAnimationFrame(() => {
      if (containerRef.current) attachToContainer(containerRef.current);
    });
  }

  async function close(id: string) {
    await closeSession(id);
    requestAnimationFrame(() => {
      if (containerRef.current && getActiveSession()) {
        attachToContainer(containerRef.current);
      }
    });
  }

  useEffect(() => {
    const onResize = () => window.setTimeout(fitActiveSession, 100);
    window.addEventListener("resize", onResize);
    if (containerRef.current && getActiveSession()) {
      requestAnimationFrame(() => {
        if (containerRef.current) attachToContainer(containerRef.current);
      });
    }
    return () => {
      window.removeEventListener("resize", onResize);
      detachFromContainer();
    };
  }, []);

  return (
    <div className="flex flex-col h-full">
      <div className="flex items-center justify-between px-4 py-3 border-b border-border bg-bg-secondary shrink-0">
        <div className="flex items-center gap-3">
          <ProjectPicker />
          <ActionButton onClick={startNew} disabled={!projectPath || starting} variant="primary">
            <Plus size={14} />
            {starting ? "Starting..." : "New Session"}
          </ActionButton>
        </div>
        {error && <span className="text-xs text-danger">{error}</span>}
      </div>

      {sessions.length > 0 && (
        <div className="flex items-center gap-1 px-3 py-1.5 border-b border-border bg-bg-secondary/50 shrink-0 overflow-x-auto">
          {sessions.map((session) => (
            <button
              key={session.id}
              type="button"
              className={`flex items-center gap-1.5 pl-3 pr-1 py-1 text-xs rounded-md transition-colors shrink-0 ${
                activeId === session.id
                  ? "bg-bg-tertiary text-text-primary"
                  : "text-text-muted hover:text-text-secondary hover:bg-bg-hover"
              }`}
              onClick={() => selectSession(session.id)}
            >
              <span
                className={`w-1.5 h-1.5 rounded-full ${session.alive ? "bg-success" : "bg-text-muted"}`}
              />
              <span className="max-w-32 truncate">{session.projectName}</span>
              <span
                role="button"
                tabIndex={0}
                className="ml-1 p-0.5 rounded hover:bg-bg-hover text-text-muted hover:text-danger"
                onClick={(event) => {
                  event.stopPropagation();
                  void close(session.id);
                }}
                onKeyDown={(event) => {
                  if (event.key === "Enter") {
                    event.stopPropagation();
                    void close(session.id);
                  }
                }}
                aria-label="Close session"
              >
                <X size={12} />
              </span>
            </button>
          ))}
        </div>
      )}

      <div className="flex-1 relative bg-[#0d1117]">
        {sessions.length === 0 && (
          <div className="absolute inset-0 flex flex-col items-center justify-center text-text-muted">
            <TerminalIcon size={56} className="mb-4 opacity-20" />
            <p className="text-sm mb-1">
              {projectPath ? "Click New Session to start" : "Select a project first"}
            </p>
            <p className="text-xs text-text-muted">Sessions persist when you navigate away</p>
          </div>
        )}
        <div
          ref={containerRef}
          className={`absolute inset-0 ${sessions.length === 0 ? "hidden" : ""}`}
        />
      </div>
    </div>
  );
}

// src/lib/components/terminal/TerminalPage.svelte
<script lang="ts">
  import "@xterm/xterm/css/xterm.css";
  import { onMount, onDestroy } from "svelte";
  import ProjectPicker from "$lib/components/shared/ProjectPicker.svelte";
  import { getSelectedProjectPath, getSelectedProjectName } from "$lib/stores/project-context.svelte";
  import {
    getSessions,
    getActiveSessionId,
    getActiveSession,
    createSession,
    closeSession,
    switchSession,
    attachToContainer,
    detachFromContainer,
    fitActiveSession,
  } from "$lib/stores/terminal.svelte";
  import { X } from "lucide-svelte";

  let terminalContainer: HTMLDivElement;
  let starting = $state(false);
  let error = $state<string | null>(null);

  const projectPath = $derived(getSelectedProjectPath());
  const projectName = $derived(getSelectedProjectName());
  const sessions = $derived(getSessions());
  const activeId = $derived(getActiveSessionId());
  const activeSession = $derived(getActiveSession());

  async function startNew() {
    if (!projectPath || starting) return;
    starting = true;
    error = null;
    try {
      await createSession(projectPath, projectName);
      // Attach to container
      requestAnimationFrame(() => {
        if (terminalContainer) attachToContainer(terminalContainer);
      });
    } catch (e) {
      error = `Failed to start: ${e}`;
    } finally {
      starting = false;
    }
  }

  function handleTabSwitch(id: string) {
    detachFromContainer();
    switchSession(id);
    requestAnimationFrame(() => {
      if (terminalContainer) attachToContainer(terminalContainer);
    });
  }

  async function handleClose(id: string) {
    await closeSession(id);
    requestAnimationFrame(() => {
      if (terminalContainer && getActiveSession()) {
        attachToContainer(terminalContainer);
      }
    });
  }

  let resizeTimer: ReturnType<typeof setTimeout> | null = null;
  function handleResize() {
    if (resizeTimer) clearTimeout(resizeTimer);
    resizeTimer = setTimeout(() => fitActiveSession(), 100);
  }

  onMount(() => {
    window.addEventListener("resize", handleResize);
    // Re-attach existing session if coming back to terminal tab
    if (activeSession && terminalContainer) {
      requestAnimationFrame(() => attachToContainer(terminalContainer));
    }
  });

  onDestroy(() => {
    window.removeEventListener("resize", handleResize);
    // Detach but DON'T kill — session stays alive
    detachFromContainer();
  });
</script>

<div class="flex flex-col h-full">
  <!-- Top bar: project picker + new -->
  <div class="flex items-center justify-between px-4 py-3 border-b border-border bg-bg-secondary shrink-0">
    <div class="flex items-center gap-3">
      <ProjectPicker onselect={() => {}} />
      <button
        class="px-3 py-1.5 text-xs bg-accent hover:bg-accent-hover text-white rounded-md transition-colors disabled:opacity-50 shrink-0"
        onclick={startNew}
        disabled={!projectPath || starting}
      >
        {starting ? "Starting..." : "+ New Session"}
      </button>
    </div>
    {#if error}
      <span class="text-xs text-danger">{error}</span>
    {/if}
  </div>

  <!-- Session tabs -->
  {#if sessions.length > 0}
    <div class="flex items-center gap-1 px-3 py-1.5 border-b border-border bg-bg-secondary/50 shrink-0 overflow-x-auto">
      {#each sessions as session}
        <div
          class="flex items-center gap-1.5 pl-3 pr-1 py-1 text-xs rounded-md transition-colors shrink-0 cursor-pointer
            {activeId === session.id
              ? 'bg-bg-tertiary text-text-primary'
              : 'text-text-muted hover:text-text-secondary hover:bg-bg-hover'}"
          role="tab"
          tabindex="0"
          onclick={() => handleTabSwitch(session.id)}
          onkeydown={(e) => e.key === "Enter" && handleTabSwitch(session.id)}
        >
          <span class="w-1.5 h-1.5 rounded-full {session.alive ? 'bg-success' : 'bg-text-muted'}"></span>
          <span class="max-w-32 truncate">{session.projectName}</span>
          <button
            class="ml-1 p-0.5 rounded hover:bg-bg-hover text-text-muted hover:text-danger"
            onclick={(e) => { e.stopPropagation(); handleClose(session.id); }}
            aria-label="Close session"
          >
            <X size={12} />
          </button>
        </div>
      {/each}
    </div>
  {/if}

  <!-- Terminal area -->
  <div class="flex-1 relative bg-[#0d1117]">
    {#if sessions.length === 0}
      <div class="absolute inset-0 flex flex-col items-center justify-center text-text-muted">
        <svg class="w-16 h-16 mb-4 opacity-20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
          <path d="M4 17l6-6-6-6M12 19h8" />
        </svg>
        <p class="text-sm mb-1">{projectPath ? "Click + New to start a session" : "Select a project first"}</p>
        <p class="text-xs text-text-muted">Sessions persist when you navigate away</p>
      </div>
    {/if}
    <div
      bind:this={terminalContainer}
      class="absolute inset-0"
      class:hidden={sessions.length === 0}
    ></div>
  </div>
</div>
